//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hermesmvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actual> Actuals { get; set; }
        public virtual DbSet<BaseSale> BaseSales { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<BuildVersion> BuildVersions { get; set; }
        public virtual DbSet<Channel> Channels { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomersDetail> CustomersDetails { get; set; }
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<FixedTE> FixedTEs { get; set; }
        public virtual DbSet<FixedTE_details> FixedTE_details { get; set; }
        public virtual DbSet<FixedTE_types> FixedTE_types { get; set; }
        public virtual DbSet<Period> Periods { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductsPrice> ProductsPrices { get; set; }
        public virtual DbSet<PromoGroup> PromoGroups { get; set; }
        public virtual DbSet<Promotion> Promotions { get; set; }
        public virtual DbSet<PromotionsDetail> PromotionsDetails { get; set; }
        public virtual DbSet<PromotionsStatus> PromotionsStatuses { get; set; }
        public virtual DbSet<PromotionsType> PromotionsTypes { get; set; }
        public virtual DbSet<Segment> Segments { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Technology> Technologies { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
