//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hermesmvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Actuals = new HashSet<Actual>();
            this.ProductsPrices = new HashSet<ProductsPrice>();
            this.PromotionsDetails = new HashSet<PromotionsDetail>();
        }
    
        public int id { get; set; }
        public string internal_code_1 { get; set; }
        public string internal_code_2 { get; set; }
        public string ean { get; set; }
        public bool deactive { get; set; }
        public int promogroup_id { get; set; }
        public string size { get; set; }
        public string name { get; set; }
        public int casecount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actual> Actuals { get; set; }
        public virtual PromoGroup PromoGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsPrice> ProductsPrices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromotionsDetail> PromotionsDetails { get; set; }
    }
}
