//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hermesgroupmvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseSale
    {
        public int id { get; set; }
        public int customer_id { get; set; }
        public int promogroup_id { get; set; }
        public int period_id { get; set; }
        public double value { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual PromoGroup PromoGroup { get; set; }
        public virtual Period Period { get; set; }
    }
}
