//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hermesgroupmvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomersDetail
    {
        public int id { get; set; }
        public string shipto { get; set; }
        public string soldto { get; set; }
        public string address { get; set; }
        public string telephone { get; set; }
        public int customer_id { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
