//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hermesgroupmvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vFixedTE
    {
        public int customer_id { get; set; }
        public int segment_id { get; set; }
        public int year { get; set; }
        public double on_te { get; set; }
        public double off_te { get; set; }
    }
}
