//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hermesgroupmvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPromotionsDetailsCalculation
    {
        public int customer_id { get; set; }
        public int product_id { get; set; }
        public int volume { get; set; }
        public Nullable<double> gsv { get; set; }
        public Nullable<double> niv { get; set; }
        public Nullable<double> nsv { get; set; }
        public Nullable<double> te { get; set; }
        public Nullable<double> te_perc { get; set; }
        public Nullable<double> mmac { get; set; }
        public Nullable<double> mmac_perc { get; set; }
    }
}
